#!/usr/bin/env node

/**
 * Wix Environment Setup Script
 * 
 * This script helps you create a .env.local file with the correct Wix API credentials.
 * Run this script with: node scripts/setup-env.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const envPath = path.join(process.cwd(), '.env.local');

console.log('🚀 Wix API Environment Setup');
console.log('============================\n');

// Check if .env.local already exists
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env.local file already exists!');
  rl.question('Do you want to overwrite it? (y/N): ', (answer) => {
    if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
      createEnvFile();
    } else {
      console.log('Setup cancelled.');
      rl.close();
    }
  });
} else {
  createEnvFile();
}

function createEnvFile() {
  console.log('\n📝 Please provide your Wix API credentials:');
  console.log('(Press Enter to use default values where applicable)\n');

  rl.question('Wix API Key (required): ', (apiKey) => {
    if (!apiKey.trim()) {
      console.log('❌ API Key is required! Please run the script again.');
      rl.close();
      return;
    }

    const envContent = `# Wix API Credentials
# Generated by setup script on ${new Date().toISOString()}

# Required: Your Wix Client ID (from Wix Developer Center)
WIX_CLIENT_ID=8a36ba43-6e83-4992-bc2c-8ebd8726f85b

# Required: Your Wix Site ID (from dashboard URL)
WIX_SITE_ID=e3587e8a-ac64-44d8-952f-14001d3dd2f6

# Required: Your Wix API Key (from Wix Developer Center)
WIX_API_KEY=${apiKey.trim()}

# Instructions:
# 1. Make sure your API key has the necessary permissions for Stores API
# 2. Restart your development server after creating this file
# 3. For detailed setup instructions, see WIX_SETUP.md
`;

    try {
      fs.writeFileSync(envPath, envContent);
      console.log('\n✅ .env.local file created successfully!');
      console.log('\n📋 Next steps:');
      console.log('1. Restart your development server (npm run dev)');
      console.log('2. Navigate to /products to test the integration');
      console.log('3. Check the browser console for any errors');
      console.log('\n📖 For detailed setup instructions, see WIX_SETUP.md');
    } catch (error) {
      console.error('❌ Error creating .env.local file:', error.message);
    }

    rl.close();
  });
}
